### PR TITLE
Drop a redundant step from Helm exporter blog post

### PR DESCRIPTION
**Pull request by zeenix**
You don't need to install the habitat-operator explicitly.

Signed-off-by: Zeeshan Ali <zeeshan@kinvolk.io>

### CODE REVIEW

**Comment by zeenix** [comment]
Context: https://github.com/habitat-sh/habitat/pull/4664#issuecomment-369109512 .

**Review by lilic — APPROVED** [review]
> You don't need to install the habitat-operator explicitly.

I would explain why in the commit msg a bit more in detail. Why don't you need to install it explicitly. 

Other then that feel free to file upstream.

**Comment by zeenix** [comment]
Updated the commit message.

**Comment by zeenix** [comment]
https://github.com/habitat-sh/habitat/pull/4690

**Pull request closed without merging**
