### PR TITLE
pkg-export-k8s: Remove redundant newline filtering code

### PR DESCRIPTION
**Pull request by zeenix**
Instead use the means provided by Handlebars templating language to
achieve the same in the source template itself.

Signed-off-by: Zeeshan Ali <zeeshan@kinvolk.io>

### CODE REVIEW

**Review by asymmetric — COMMENTED** [review]
If it works, LGTM.

**Comment by zeenix** [comment]
@asymmetric thanks. It does work afaict. I ran the `cargo test` and manually tested too.

**Comment by krnowak** [comment]
LFAD.

**Review by asymmetric — APPROVED** [review]

**Comment by zeenix** [comment]
Thanks. Upstreamed: https://github.com/habitat-sh/habitat/pull/4648

**Pull request closed without merging**
