### PR TITLE
Allow skipping the initial event in file watcher

### PR DESCRIPTION
**Pull request by krnowak**
Signed-off-by: Krzesimir Nowak <krzesimir@kinvolk.io>

### CODE REVIEW

**Comment by asymmetric** [comment]
I cherry-picked this into my branch, so should we close?

**Comment by asymmetric** [comment]
Also, as it is this produces a warning for unused code.

**Comment by krnowak** [comment]
Yeah, because nothing uses it, but you will. ;)

**Comment by krnowak** [comment]
You can close it if you have no issues.

**Pull request closed without merging**
