### PR TITLE
Docs+blog post update

### PR DESCRIPTION
**Pull request by zeenix**
This PR updates:

* URL for the Habitat-Operator in the docs and blog posts.
* Instructions for Helm exporter usage in the announcement blog post as per changes in 0.55 release.

### CODE REVIEW

**Review by asymmetric — APPROVED** [review]

**Comment by krnowak** [comment]
@zeenix: There is a line in `www/source/blog/2018-02-21-Habitat-Helm.html.md`: `helm repo add habitat-operator https://kinvolk.github.io/habitat-operator/helm/charts/stable/`, should this be changed too? It mentions kinvolk github page…

**Comment by zeenix** [comment]
@krnowak ah, good catch. Yes. I think so.

**Comment by zeenix** [comment]
@krnowak fixed. I'll file upstream

**Comment by zeenix** [comment]
https://github.com/habitat-sh/habitat/pull/4820

**Pull request closed without merging**
